import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SsoReceiver from "@/components/SsoReceiver";
import "./globals.css";

const getSsoUrl = () => {
  if (typeof window !== "undefined" && window.location.hostname !== "localhost") {
    // 1. Ambil origin saat ini secara otomatis (mendukung localhost maupun Vercel)
const getSsoLoginUrl = () => {
  const isProduction = typeof window !== "undefined" && window.location.hostname !== "localhost";
  
  // URL SSO saat online (Ganti dengan domain Vercel pusat-akun-sso Anda nanti, atau gunakan env var)
  const baseSsoUrl = process.env.NEXT_PUBLIC_SSO_URL || "http://localhost:3000";
  
  // Tentukan URL tujuan kembali (callback) ke aplikasi toko saat ini
  const currentOrigin = typeof window !== "undefined" ? window.location.origin : "http://localhost:3001";

  return `${baseSsoUrl}/?source=toko&next=${encodeURIComponent(currentOrigin)}`;
};

// Gunakan fungsi di dalam komponen atau variabel konstan
const SSO_LOGIN_URL = getSsoLoginUrl();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SsoReceiver />
        {children}
      </body>
    </html>
  );
}
